export const countAT = {
  GET_COUNTRIES: 'GET_COUNTRIES',
  GETTING_COUNTRIES: 'GETTING_COUNTRIES',

  GET_COUNTRY_CASES: 'GET_COUNTRY_CASES',
  GETTING_COUNTRY_CASES: 'GETTING_COUNTRY_CASES',

  GET_CASES_BY_COUNTRY_NAME: 'GET_CASES_BY_COUNTRY_NAME',
  GETTING_CASES_BY_COUNTRY_NAME: 'GETTING_CASES_BY_COUNTRY_NAME',
};
