export const countAT = {
  GET_MOST_RECENT_CASE: 'GET_MOST_RECENT_CASE',
  CLEAN_MOST_RECENT_CASE: 'CLEAN_MOST_RECENT_CASE',
  GETTING_MOST_RECENT_CASE: 'GETTING_MOST_RECENT_CASE',

  GET_COUNTRIES: 'GET_COUNTRIES',
  GETTING_COUNTRIES: 'GETTING_COUNTRIES',

  GET_ACTIVE_COUNTRY_CASES: 'GET_ACTIVE_COUNTRY_CASES',
  GETTING_ACTIVE_COUNTRY_CASES: 'GETTING_ACTIVE_COUNTRY_CASES',
  CLEAN_ACTIVE_COUNTRY_CASES: 'CLEAN_ACTIVE_COUNTRY_CASES',

  GET_CASES_BY_COUNTRY_NAME: 'GET_CASES_BY_COUNTRY_NAME',
  GETTING_CASES_BY_COUNTRY_NAME: 'GETTING_CASES_BY_COUNTRY_NAME',
};
